version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_DB=kotlin_ddd_testing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build:
      context: ./../../
      dockerfile: ./.github/ci/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local