version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: backendddtesting
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  db:
    driver: local
