name: Kotlin gradle CI

on: [push]

jobs:
  test:
    name: Run unit and integration test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up kotlin
        uses: fwilhe2/setup-kotlin@main
      - name: Launch unit test
        run: ./gradlew cleanTest test
      - name: Launch integration tests
        run: |
          docker run -i --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME:$HOME" \
            -v "$PWD:$PWD" \
            -w "$PWD" \
            openjdk:18-jdk-alpine \
            ./gradlew cleanIntegrationTest integrationTest
      - name: Launch E2E tests
        run: ./gradlew e2eTest
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up kotlin
        uses: fwilhe2/setup-kotlin@main
      - name: Build with Gradle
        run: ./gradlew build -x test -x integrationTest -x e2eTest
